<?php

namespace ContainerUliKfz6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QRaGVEHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qRaGVEH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qRaGVEH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ApiCrearOds::create' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ApiCrearOds::create()', 'getApiCrearOdscreateService', true],
            'App\\Controller\\ApiOdsController::getOds' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ApiOdsController::getOds()', 'getApiOdsControllergetOdsService', true],
            'App\\Controller\\AuthController::register' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\AuthController::register()', 'getAuthControllerregisterService', true],
            'App\\Controller\\AuthController::login' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\AuthController::login()', 'getAuthControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ApiCrearOds:create' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ApiCrearOds::create()', 'getApiCrearOdscreateService', true],
            'App\\Controller\\ApiOdsController:getOds' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ApiOdsController::getOds()', 'getApiOdsControllergetOdsService', true],
            'App\\Controller\\AuthController:register' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\AuthController::register()', 'getAuthControllerregisterService', true],
            'App\\Controller\\AuthController:login' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\AuthController::login()', 'getAuthControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ApiCrearOds::create' => '?',
            'App\\Controller\\ApiOdsController::getOds' => '?',
            'App\\Controller\\AuthController::register' => '?',
            'App\\Controller\\AuthController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ApiCrearOds:create' => '?',
            'App\\Controller\\ApiOdsController:getOds' => '?',
            'App\\Controller\\AuthController:register' => '?',
            'App\\Controller\\AuthController:login' => '?',
        ]);
    }
}
