<?php

namespace ContainerUliKfz6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPentatrionVite_EntrypointsLookupappService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'pentatrion_vite.entrypoints_lookup[app]' shared service.
     *
     * @return \Pentatrion\ViteBundle\Service\EntrypointsLookup
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pentatrion'.\DIRECTORY_SEPARATOR.'vite-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'EntrypointsLookup.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pentatrion'.\DIRECTORY_SEPARATOR.'vite-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'FileAccessor.php';

        return $container->privates['pentatrion_vite.entrypoints_lookup[app]'] = new \Pentatrion\ViteBundle\Service\EntrypointsLookup(new \Pentatrion\ViteBundle\Service\FileAccessor((\dirname(__DIR__, 4).'/C:'.\DIRECTORY_SEPARATOR.'Users'.\DIRECTORY_SEPARATOR.'Mati'.\DIRECTORY_SEPARATOR.'Desktop'.\DIRECTORY_SEPARATOR.'odspol'.\DIRECTORY_SEPARATOR.'ODS/public'), $container->parameters['pentatrion_vite.configs'], NULL), 'app', false);
    }
}
