<?php

namespace ContainerNcZEMf5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPentatrionVite_CacheWarmerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'pentatrion_vite.cache_warmer' shared service.
     *
     * @return \Pentatrion\ViteBundle\CacheWarmer\EntrypointsCacheWarmer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'CacheWarmer'.\DIRECTORY_SEPARATOR.'CacheWarmerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'CacheWarmer'.\DIRECTORY_SEPARATOR.'AbstractPhpFileCacheWarmer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pentatrion'.\DIRECTORY_SEPARATOR.'vite-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'CacheWarmer'.\DIRECTORY_SEPARATOR.'EntrypointsCacheWarmer.php';

        return $container->privates['pentatrion_vite.cache_warmer'] = new \Pentatrion\ViteBundle\CacheWarmer\EntrypointsCacheWarmer((\dirname(__DIR__, 4).'/C:'.\DIRECTORY_SEPARATOR.'Users'.\DIRECTORY_SEPARATOR.'Mati'.\DIRECTORY_SEPARATOR.'Desktop'.\DIRECTORY_SEPARATOR.'odspol'.\DIRECTORY_SEPARATOR.'ODS/public'), $container->parameters['pentatrion_vite.configs'], ($container->targetDir.''.'/pentatrion_vite.cache.php'));
    }
}
