<?php

namespace Container9Sy1Sxh;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPentatrionVite_TagRendererappService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'pentatrion_vite.tag_renderer[app]' shared service.
     *
     * @return \Pentatrion\ViteBundle\Service\TagRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pentatrion'.\DIRECTORY_SEPARATOR.'vite-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TagRenderer.php';

        return $container->privates['pentatrion_vite.tag_renderer[app]'] = new \Pentatrion\ViteBundle\Service\TagRenderer(['crossorigin' => true], [], [], [], 'link-tag');
    }
}
