<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUliKfz6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUliKfz6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUliKfz6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUliKfz6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUliKfz6\App_KernelDevDebugContainer([
    'container.build_hash' => 'UliKfz6',
    'container.build_id' => '555bf59d',
    'container.build_time' => 1764848864,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUliKfz6');
