<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7woETf1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7woETf1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7woETf1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7woETf1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7woETf1\App_KernelDevDebugContainer([
    'container.build_hash' => '7woETf1',
    'container.build_id' => 'c82c9aa0',
    'container.build_time' => 1764765128,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container7woETf1');
