<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container14QSc8z\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container14QSc8z/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container14QSc8z.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container14QSc8z\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container14QSc8z\App_KernelDevDebugContainer([
    'container.build_hash' => '14QSc8z',
    'container.build_id' => '350ef38c',
    'container.build_time' => 1764754672,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container14QSc8z');
