<?php

namespace Container1t9lyHH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfilerController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Pentatrion\ViteBundle\Controller\ProfilerController' shared service.
     *
     * @return \Pentatrion\ViteBundle\Controller\ProfilerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pentatrion'.\DIRECTORY_SEPARATOR.'vite-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ProfilerController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pentatrion'.\DIRECTORY_SEPARATOR.'vite-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Debug.php';

        return $container->services['Pentatrion\\ViteBundle\\Controller\\ProfilerController'] = new \Pentatrion\ViteBundle\Controller\ProfilerController(new \Pentatrion\ViteBundle\Service\Debug($container->parameters['pentatrion_vite.configs'], ($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->privates['pentatrion_vite.entrypoints_lookup_collection'] ?? self::getPentatrionVite_EntrypointsLookupCollectionService($container)), NULL), ($container->privates['twig'] ?? self::getTwigService($container)));
    }
}
